courses = [
    {
        "course_id": 1,
        "course_code": "CSC 1301",
        "course_title": "Introduction to Computing Principles",
        "department": "Computer Science",
        "credits": 3,
        "difficulty": 2,
        "description": "An introduction to computer science concepts including programming fundamentals, algorithms, and problem-solving using Python.",
    },
    {
        "course_id": 2,
        "course_code": "CSC 2310",
        "course_title": "Introduction to Programming",
        "department": "Computer Science",
        "credits": 3,
        "difficulty": 3,
        "description": "Covers object-oriented programming in Java, including classes, inheritance, polymorphism, and basic data structures.",
    },
    {
        "course_id": 3,
        "course_code": "CSC 3410",
        "course_title": "Data Structures",
        "department": "Computer Science",
        "credits": 3,
        "difficulty": 4,
        "description": "Study of fundamental data structures including lists, stacks, queues, trees, and graphs with implementation in Java or C++.",
    },
    {
        "course_id": 4,
        "course_code": "CSC 4330",
        "course_title": "Software Engineering",
        "department": "Computer Science",
        "credits": 3,
        "difficulty": 3,
        "description": "Principles of software development including requirements analysis, system design, testing, and project management.",
    },
    {
        "course_id": 5,
        "course_code": "MATH 2211",
        "course_title": "Calculus of One Variable I",
        "department": "Mathematics",
        "credits": 4,
        "difficulty": 4,
        "description": "Limits, continuity, derivatives, and integrals of functions of one variable with applications.",
    },
    {
        "course_id": 6,
        "course_code": "MATH 2212",
        "course_title": "Calculus of One Variable II",
        "department": "Mathematics",
        "credits": 4,
        "difficulty": 4,
        "description": "Techniques of integration, sequences and series, parametric equations, polar coordinates, and introductory differential equations.",
    },
    {
        "course_id": 7,
        "course_code": "MATH 3260",
        "course_title": "Linear Algebra",
        "department": "Mathematics",
        "credits": 3,
        "difficulty": 3,
        "description": "Systems of linear equations, matrices, determinants, vector spaces, eigenvalues, and eigenvectors.",
    },
    {
        "course_id": 8,
        "course_code": "BIOL 1107",
        "course_title": "Principles of Biology I",
        "department": "Biology",
        "credits": 4,
        "difficulty": 3,
        "description": "Introduction to cell biology, genetics, evolution, and diversity of life with a required laboratory component.",
    },
    {
        "course_id": 9,
        "course_code": "BIOL 1108",
        "course_title": "Principles of Biology II",
        "department": "Biology",
        "credits": 4,
        "difficulty": 3,
        "description": "Plant and animal physiology, ecology, and behavior. Continuation of BIOL 1107 with lab.",
    },
    {
        "course_id": 10,
        "course_code": "ENGL 1101",
        "course_title": "English Composition I",
        "department": "English",
        "credits": 3,
        "difficulty": 2,
        "description": "Fundamentals of college writing, critical reading, and argumentative essay composition.",
    },
    {
        "course_id": 11,
        "course_code": "ENGL 1102",
        "course_title": "English Composition II",
        "department": "English",
        "credits": 3,
        "difficulty": 2,
        "description": "Advanced composition with emphasis on research writing, literary analysis, and academic argument.",
    },
    {
        "course_id": 12,
        "course_code": "PHYS 2211",
        "course_title": "Introduction to Physics I",
        "department": "Physics",
        "credits": 4,
        "difficulty": 4,
        "description": "Classical mechanics, kinematics, dynamics, work and energy, momentum, rotation, and gravitation. Calculus-based.",
    },
    {
        "course_id": 13,
        "course_code": "PSYC 1101",
        "course_title": "Introduction to Psychology",
        "department": "Psychology",
        "credits": 3,
        "difficulty": 2,
        "description": "Overview of psychology including biological bases of behavior, perception, learning, memory, personality, and social behavior.",
    },
    {
        "course_id": 14,
        "course_code": "HIST 1111",
        "course_title": "World History to 1500",
        "department": "History",
        "credits": 3,
        "difficulty": 2,
        "description": "Survey of world civilizations from prehistoric times through the early modern period.",
    },
    {
        "course_id": 15,
        "course_code": "CSC 4520",
        "course_title": "Design and Analysis of Algorithms",
        "department": "Computer Science",
        "credits": 3,
        "difficulty": 5,
        "description": "Algorithm design paradigms including divide-and-conquer, dynamic programming, greedy algorithms, and computational complexity theory.",
    },
]

professors = [
    {
        "professor_id": 1,
        "name": "Dr. Angela Foster",
        "department": "Computer Science",
        "rating": 4.7,
        "difficulty": 3,
        "bio": "Specializes in software engineering and human-computer interaction. Known for engaging lectures and real-world project assignments.",
    },
    {
        "professor_id": 2,
        "name": "Dr. Marcus Webb",
        "department": "Computer Science",
        "rating": 4.2,
        "difficulty": 4,
        "bio": "Expert in algorithms and theoretical computer science. Challenging but fair grader with detailed feedback.",
    },
    {
        "professor_id": 3,
        "name": "Dr. Linda Okafor",
        "department": "Mathematics",
        "rating": 4.5,
        "difficulty": 3,
        "bio": "Calculus and linear algebra specialist. Renowned for breaking down complex proofs into understandable steps.",
    },
    {
        "professor_id": 4,
        "name": "Dr. James Chen",
        "department": "Mathematics",
        "rating": 3.8,
        "difficulty": 5,
        "bio": "Research-focused professor in applied mathematics. Courses are rigorous with high expectations for mathematical maturity.",
    },
    {
        "professor_id": 5,
        "name": "Dr. Priya Nair",
        "department": "Biology",
        "rating": 4.6,
        "difficulty": 3,
        "bio": "Molecular biologist with a passion for genetics and cell biology. Engaging lab sessions and clear lecture notes.",
    },
    {
        "professor_id": 6,
        "name": "Prof. Derek Hamilton",
        "department": "English",
        "rating": 4.8,
        "difficulty": 2,
        "bio": "Veteran composition instructor with 20+ years of experience. Provides thorough feedback on all written work.",
    },
    {
        "professor_id": 7,
        "name": "Dr. Sofia Reyes",
        "department": "Physics",
        "rating": 4.1,
        "difficulty": 4,
        "bio": "Experimental physicist specializing in classical mechanics. Labs are comprehensive and reinforce lecture concepts.",
    },
    {
        "professor_id": 8,
        "name": "Dr. Kevin Asante",
        "department": "Psychology",
        "rating": 4.9,
        "difficulty": 2,
        "bio": "Cognitive psychologist and author of widely used textbooks. Extremely popular for approachable teaching style.",
    },
]

sections = [
    # CSC 1301 - Dr. Foster
    {
        "section_id": 1,
        "course_id": 1,
        "professor_id": 1,
        "semester": "Fall 2025",
        "meeting_times": "MWF 9:00 AM - 9:50 AM",
    },
    # CSC 1301 - Dr. Webb
    {
        "section_id": 2,
        "course_id": 1,
        "professor_id": 2,
        "semester": "Fall 2025",
        "meeting_times": "TR 2:00 PM - 3:15 PM",
    },
    # CSC 2310 - Dr. Foster
    {
        "section_id": 3,
        "course_id": 2,
        "professor_id": 1,
        "semester": "Fall 2025",
        "meeting_times": "MWF 11:00 AM - 11:50 AM",
    },
    # CSC 3410 - Dr. Webb
    {
        "section_id": 4,
        "course_id": 3,
        "professor_id": 2,
        "semester": "Fall 2025",
        "meeting_times": "TR 4:00 PM - 5:15 PM",
    },
    # CSC 4330 - Dr. Foster
    {
        "section_id": 5,
        "course_id": 4,
        "professor_id": 1,
        "semester": "Fall 2025",
        "meeting_times": "MWF 1:00 PM - 1:50 PM",
    },
    # MATH 2211 - Dr. Okafor
    {
        "section_id": 6,
        "course_id": 5,
        "professor_id": 3,
        "semester": "Fall 2025",
        "meeting_times": "MWF 8:00 AM - 8:50 AM",
    },
    # MATH 2211 - Dr. Chen
    {
        "section_id": 7,
        "course_id": 5,
        "professor_id": 4,
        "semester": "Fall 2025",
        "meeting_times": "TR 10:00 AM - 11:15 AM",
    },
    # MATH 2212 - Dr. Okafor
    {
        "section_id": 8,
        "course_id": 6,
        "professor_id": 3,
        "semester": "Fall 2025",
        "meeting_times": "MWF 10:00 AM - 10:50 AM",
    },
    # MATH 3260 - Dr. Chen
    {
        "section_id": 9,
        "course_id": 7,
        "professor_id": 4,
        "semester": "Fall 2025",
        "meeting_times": "TR 1:00 PM - 2:15 PM",
    },
    # BIOL 1107 - Dr. Nair
    {
        "section_id": 10,
        "course_id": 8,
        "professor_id": 5,
        "semester": "Fall 2025",
        "meeting_times": "MWF 12:00 PM - 12:50 PM",
    },
    # BIOL 1108 - Dr. Nair
    {
        "section_id": 11,
        "course_id": 9,
        "professor_id": 5,
        "semester": "Fall 2025",
        "meeting_times": "TR 8:00 AM - 9:15 AM",
    },
    # ENGL 1101 - Prof. Hamilton
    {
        "section_id": 12,
        "course_id": 10,
        "professor_id": 6,
        "semester": "Fall 2025",
        "meeting_times": "MWF 9:00 AM - 9:50 AM",
    },
    # ENGL 1102 - Prof. Hamilton
    {
        "section_id": 13,
        "course_id": 11,
        "professor_id": 6,
        "semester": "Fall 2025",
        "meeting_times": "TR 3:30 PM - 4:45 PM",
    },
    # PHYS 2211 - Dr. Reyes
    {
        "section_id": 14,
        "course_id": 12,
        "professor_id": 7,
        "semester": "Fall 2025",
        "meeting_times": "MWF 2:00 PM - 2:50 PM",
    },
    # PSYC 1101 - Dr. Asante
    {
        "section_id": 15,
        "course_id": 13,
        "professor_id": 8,
        "semester": "Fall 2025",
        "meeting_times": "TR 12:30 PM - 1:45 PM",
    },
    # HIST 1111 - (no dedicated prof, using Asante as placeholder)
    {
        "section_id": 16,
        "course_id": 14,
        "professor_id": 8,
        "semester": "Fall 2025",
        "meeting_times": "MWF 3:00 PM - 3:50 PM",
    },
    # CSC 4520 - Dr. Webb
    {
        "section_id": 17,
        "course_id": 15,
        "professor_id": 2,
        "semester": "Fall 2025",
        "meeting_times": "TR 5:30 PM - 6:45 PM",
    },
]
